DROP TABLE IF EXISTS BOOK;

CREATE TABLE BOOK (
ID BIGINT,
AUTHOR VARCHAR(100),
ISBN VARCHAR(50),
TITLE VARCHAR(100),
BORROWER_ID BIGINT,
PRIMARY KEY (ID)
);

DROP TABLE IF EXISTS BORROWER;

CREATE TABLE BORROWER (
ID BIGINT,
EMAIL VARCHAR(50),
NAME VARCHAR(50),
PRIMARY KEY (ID)
);