DROP TABLE IF EXISTS book;

create table book (
borrower_id bigint, 
id bigint generated by default as identity, 
author varchar(255) not null, 
isbn varchar(255) not null, 
title varchar(255) not null, 
primary key (id)
);

DROP TABLE IF EXISTS borrower;

create table borrower (
id bigint generated by default as identity, 
email varchar(255) not null unique, 
name varchar(255) not null unique, 
primary key (id)
);

alter table if exists book add constraint FK_BOOK foreign key (borrower_id) references borrower;